title: "風 林 火 山"
tagline: "陸家林 Lu Jialin"
description: "Homepage of Lu Jialin 陸家林"
url:
baseurl: ""
author: "Jialin Lu"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
